name: Update redirect files
description: |
  Update HTML documents in the repository which describe Go import path redirect.
runs:
  using: node24
  main: ../dist/update/index.js
author: ikura-hamu
inputs:
  pages_dir:
    default: '.'
    description: Directory containing HTML documents.
  payload:
    description: JSON payload to update the documents.
    required: true
  change_type:
    default: 'commit'
    description: |
      Type of change to make (`commit` | `pr`).
      If `pr`, create a new branch and a pull request will be created.
      If `commit`, changes will be committed and pushed to the current branch.
  github_token:
    description: GITHUB_TOKEN
    required: true
